<?php
/**
 * @file proxythis.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_menu().
 */
function proxythis_menu() {
  $items = array();
  $path = variable_get('proxythis_path', $default = 'proxythis');
  $title = variable_get('proxythis_title', $defualt = 'Proxy URL Converter.');
  $items[$path] = array(
    'title' => $title,
    'page callback' => 'proxythis_view',
    'access callback' => TRUE,
    );
  

  $items['admin/config/proxythis'] = array(
    'title' => 'ProxyThis Module',
    'description' => 'Settings for the proxy this module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => 'proxythis_admin_settings',
    'accees callback' => array('access administration pages'),

    );  
  return $items;
}

function proxythis_view(){
  $form =  drupal_get_form('proxythis_form');
  
  return $form;
}


function proxythis_form($form, &$form_state){
  var_dump($form_state);
  $form['url'] = array(
      '#title' => t('URL to be Converted'),
      '#type' => 'textfield',
      '#requiered' => TRUE,
      '#default_value' => '',
      '#attributes' => array(
        'placeholder' =>'http://www.example.com'
        ),
    );
  if($form_state['submitted']){
    $form['url']['#disabled'] = TRUE;
    $form['url']['#title'] = t('Original URL');
    $form['url']['#attributes']['value'] = $form_state['values']['url'];
    $form['result'] = array(
        '#title' => t('Converted URL'),
        '#type' => 'textfield',
        '#disabled' => TRUE,
        '#attributes'=> array(
          'value' => $form_state['values']['url'] . ' something more!',
          ),


      );
  }
  
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
    );
  
  
  return $form;


}

function proxythis_form_submit($form, &$form_state){
  $form_state['rebuild'] = TRUE;
}


