<?php
/**
 * @file proxythis.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_menu().
 */
function proxythis_menu() {
  $items = array();
  $path = variable_get('proxythis_path', $default = 'proxythis');
  $title = variable_get('proxythis_title', $defualt = 'Proxy URL Converter.');
  $items[$path] = array(
    'title' => $title,
    'page callback' => 'proxythis_view',
    'access callback' => TRUE,
    );
  

  $items['admin/config/proxythis'] = array(
    'title' => 'ProxyThis Module',
    'description' => 'Settings for the proxy this module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('proxythis_admin_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    );  
  return $items;
}

function proxythis_view(){
  $form =  drupal_get_form('proxythis_form');
  
  return $form;
}


function proxythis_form($form, &$form_state){
  
  $form['url'] = array(
      '#title' => t('URL to be Converted'),
      '#type' => 'textfield',
      '#requiered' => TRUE,
      '#default_value' => '',
      '#attributes' => array(
        'placeholder' =>'http://www.example.com'
        ),
    );
  if($form_state['submitted']){
    //stating a shorted variable
    $modUrl = variable_get('proxythis_pattern', $default = 'http://ezproxy.neu.edu/login?url=') . $form_state['values']['url'];

    $form['url']['#disabled'] = TRUE;
    $form['url']['#title'] = t('Original URL');
    $form['url']['#attributes']['value'] = $form_state['values']['url'];
    $form['result'] = array(
        '#title' => t('Converted URL'),
        '#type' => 'textfield',
        '#disabled' => TRUE,
        '#attributes'=> array(
          'value' => $modUrl,
          ),
        '#weight' => 10,
      );
    //get path
    $path = drupal_get_path('module','proxythis');
    $form['#attached']['js']= array(
       $path .'/js/ZeroClipboard.min.js',
       $path .'/js/init.js',
      );
    // $form['debug'] =  array(
    //   '#markup' => drupal_get_path('module','proxythis'),
    //   );
    $form['copy_link'] = array(
        '#markup' => '<a href="#" id="copy-dynamic" data-clipboard-text="'.$modUrl.'">' . t('Copy to Clipboard') . '</a>',
        '#weight' => 12, 
      );
    $form['reset'] = array(
        '#markup' => l(t('Reset'), variable_get('proxythis_path', $default = 'proxythis')),
        '#weight' => 200,
      );
  }
  
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
      '#weight' => 11, 
    );
  
  
  return $form;
}
/**
 * Submit function for proxythis_form()
 */
function proxythis_form_submit($form, &$form_state){
  $form_state['rebuild'] = TRUE;
}

/**
 * Validation function for proxythis_form()
 */
function proxythis_form_validate($form, &$form_state){
  $url = $form_state['values']['url'];
  
  //check to see if the string starts with  http:// or https:// if it does..
  if (0 !== stripos($url, 'http://') && 0 !== stripos($url, 'https://')){
    $url = 'http://'.$url;
  }

  if(0 === stripos($url, variable_get('proxythis_pattern', $default = 'http://ezproxy.neu.edu/login?url='))){
    form_set_error('url',t('This URL is already proxied, no change needed!'));
  }
  if(!filter_var($url, FILTER_VALIDATE_URL)){
    form_set_error('url',t('Please provide a valid url.'));
  }
  return $form_state['values']['url'] = $url;
}

/**
 * Builds and returns the settings form.
 */

function proxythis_admin_settings(){
  $form['proxythis_path'] = array(
      '#type' => 'textfield',
      '#title' => t('Path the form should be accessible from'),
      '#default_value' => variable_get('proxythis_path', $defualt = 'proxythis'),
      '#description' => t('@TODO'),
    );
  $form['proxythis_title'] = array(
      '#type' => 'textfield',
      '#title' => t('The title of the form page.'),
      '#default_value' => variable_get('proxythis_title', $defualt = 'Proxy URL Converter.'),
      '#description' => t('@TODO'),
    );
  $form['proxythis_pattern'] = array(
      '#type' => 'textfield',
      '#title' => t('Pattern to modify the url.'),
      '#default_value' => variable_get('proxythis_pattern', $default = 'http://ezproxy.neu.edu/login?url='),
      '#description' => t('Adds to the front of the resource link.'),
    );
  return system_settings_form($form);
}